# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f00fe2b0286379afc1cac12afab5fb67f59d9f90ffc13f8907903e02fefac7fd2d2fbeb95f153a6cc015d7e8952276188d363fabc95081e8f29e3ec612df5021

test:
  secret_key_base: 33439d0f407ff61484bd96844a8cda71a8a1c46df35325b628aa5681aeaad7ca8fdd8d8640962a44b3f3a7746e3188cfc8c7a004062f7224958382d688eab5b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
